[theme]
base = "dark"
primaryColor = "#818cf8"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0f172a"
textColor = "#f8fafc"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false
